# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Basic Tests



jobs:
  cross-browser:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Chrome browser tests
        run: npx cypress run --browser chrome --spec ./cypress/integration/basicTests.js
    
      - name: Firefox browser tests
        run: npx cypress run --browser firefox --spec ./cypress/integration/basicTests.js
        
      
