name: example-basic
on:
  push:
    paths:
    - '**basicTests.js'
jobs:
  basic-ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Firefox browser tests
        uses: cypress-io/github-action@v1
        with:
          browser: firefox
          
